name: SmartIV Hauz  Server Deployment
run-name: ${{ github.actor }} has initiated an automatic Deployment
on: [ push ]
jobs:
  automatic-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run deploy script on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd apps/smartiv_hauz_server
          chmod +x deploy.sh
          ./deploy.sh
